class DefaultConfig:
    SECRET_KEY = "dev-secret-key"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    JSON_SORT_KEYS = False
    DEFAULT_SYNC_TIMEOUT_MINUTES = 10
    MIN_SYNC_TIMEOUT_MINUTES = 1
    MAX_SYNC_TIMEOUT_MINUTES = 120
    DEFAULT_LIBRARY_RESULTS_PER_PAGE = 20
    MIN_LIBRARY_RESULTS_PER_PAGE = 1
    MAX_LIBRARY_RESULTS_PER_PAGE = 100
    DEFAULT_THEME = "dark"
